### ISSUE TITLE
0x47d/0x47d: v0.1-alpha.2 Release

### ISSUE THREAD

**Issue by 47d** [deosai/0x47d#57]
* [ ] [rm-repo: 47d/xbt.news](https://github.com/0x47d/0x47d/issues/56)
* [ ] [rm-repo: 47d/urbit.news](https://github.com/0x47d/0x47d/issues/54)
* [ ] [rm-repo: 47d/urbit.sh](https://github.com/0x47d/0x47d/issues/55)
* [ ] [rm-repo: 47d/trader.show](https://github.com/0x47d/0x47d/issues/53)
* [ ] [rm-repo: 47d/readme.wiki](https://github.com/0x47d/0x47d/issues/52)
* [ ] [rm-repo: 47d/namecoin.us](https://github.com/0x47d/0x47d/issues/51)
* [ ] [rm-repo: 47d/namecoin.co](https://github.com/0x47d/0x47d/issues/50)
* [ ] [rm-repo: 47d/hacker.show](https://github.com/0x47d/0x47d/issues/49)
* [ ] [rm-repo: 47d/freebird.im](https://github.com/0x47d/0x47d/issues/48)
* [ ] [rm-repo: 47d/compsci.news](https://github.com/0x47d/0x47d/issues/47)
* [ ] [rm-repo: 47d/chain.wiki](https://github.com/0x47d/0x47d/issues/46)
* [ ] [rm-repo: 47d/bitcoin.uk.com](https://github.com/0x47d/0x47d/issues/45)
* [ ] [rm-repo: 47d/bitcoin.team](https://github.com/0x47d/0x47d/issues/44)
* [ ] [rm-repo: 47d/bitcoin.sh](https://github.com/0x47d/0x47d/issues/43)
* [ ] [rm-repo: 47d/bitcoin.school](https://github.com/0x47d/0x47d/issues/42)
* [ ] [rm-repo: 47d/bitcoin.sa.com](https://github.com/0x47d/0x47d/issues/41)
* [ ] [rm-repo: 47d/bitcoin.qc.com](https://github.com/0x47d/0x47d/issues/40)
* [ ] [rm-repo: 47d/bitcoin.no.com](https://github.com/0x47d/0x47d/issues/39)
* [ ] [rm-repo: 47d/bitcoin.net.ag](https://github.com/0x47d/0x47d/issues/38)
* [ ] [rm-repo: 47d/bitcoin.kr.com](https://github.com/0x47d/0x47d/issues/37)
* [ ] [rm-repo: 47d/bitcoin.football](https://github.com/0x47d/0x47d/issues/36)
* [ ] [rm-repo: 47d/bitcoin.film](https://github.com/0x47d/0x47d/issues/35)
* [ ] [rm-repo: 47d/bitcoin.co.nu](https://github.com/0x47d/0x47d/issues/34)
* [ ] [rm-repo: 47d/bitcoin.co.im](https://github.com/0x47d/0x47d/issues/33)
* [ ] [rm-repo: 47d/bitcoin.com.vc](https://github.com/0x47d/0x47d/issues/32)
* [ ] [rm-repo: 47d/47d.co](https://github.com/0x47d/0x47d/issues/31)
